Feature/srv 270
YADRO-KNS/yadro-snmp pull request #4
Opened 2018-06-08 14:17 UTC by nest1ing

2018-06-13 11:48 UTC, AlexanderAmelkin requested changes

2018-06-13 11:48 UTC, AlexanderAmelkin commented on agent/yadro/software.cpp
> +                      {"Acticating", 3},
Acti**c**ating? Did you mean `Activating` ?

2018-06-13 11:48 UTC, AlexanderAmelkin commented on agent/yadro/software.cpp
> +                      "xyz.openbmc_project.Software.Actication",
What's wrong with this word? ;)

2018-06-13 11:48 UTC, AlexanderAmelkin commented on agent/yadro/software.cpp
> +                                                   0xFF, // Actication
Actication again?

2018-06-13 11:48 UTC, AlexanderAmelkin commented on configure.ac
> +        [https://github.com/YADRO-KNS/phosphor-snmp/issue])
Why did you change the URL to `/issue`? It is invalid, by the way. It should have been `/issues`, but I don't understand the reason anyway.

2018-06-13 11:48 UTC, AlexanderAmelkin commented on yadro/watcher.cpp
> +    // TODO
Ehm... we did have BMC version, now we don't have anything?

2018-06-13 12:00 UTC, nest1ing commented on configure.ac
> +        [https://github.com/YADRO-KNS/phosphor-snmp/issue])
In this field should be specified `bug-report url`.

2018-06-13 12:05 UTC, nest1ing commented on yadro/watcher.cpp
> +    // TODO
Now software with version and type present as row in `yadroSoftwareTable`.

2018-06-13 12:09 UTC, AlexanderAmelkin submitted a review, later dismissed
I'm fine with this change, but I'd like @artemsen to approve as well.

2018-06-13 14:38 UTC, AlexanderAmelkin reviewed
>  subagent: makes packages optional

Make it imperative, not 3rd person. That is, "Make packages optional"

> This functional may be used by `yocto`.

It's either "function" or "functionality", not "functional" (which is noun for a math function, or is an adjective).

2018-06-15 13:06 UTC, artemsen requested changes

2018-06-15 13:06 UTC, artemsen commented on agent/yadro/sensors.cpp
> +                                           std::get<7>(data));
Magic numbers for std::get<>(). May be we can use some identifiers (macro?) for them?

2018-06-15 13:06 UTC, artemsen commented on agent/data/table.hpp
> +     * Register MIB handlers
Function parameters description is missing.

2018-06-15 13:06 UTC, artemsen commented on agent/main.cpp
> +        print_usage();
It's a bad idea to print usage help on any errors.
By the code, function snmp_log_options() can return error but printing help is ambiguous in this case.

2018-06-15 13:06 UTC, artemsen commented on agent/main.cpp
> +    } while ((rc = evt.run(-1)) >= 0);
Bad style, I would move `rc = evt.run(-1)` to the cycle body.

2018-06-15 13:06 UTC, artemsen commented on agent/yadro/sensors.cpp
> +                snprintf(fieldOidStr, sizeof(fieldOidStr) - 1,
It would be better to make a function instead of copy/paste.

You have agent/yadro/yadro_oid.hpp with YADRO_OID macro:
#define YADRO_OID(args...)                                                     \
+    {                                                                          \
+        1, 3, 6, 1, 4, 1, 49769, ##args                                        \
+    }

2018-06-15 13:06 UTC, artemsen commented on agent/yadro/sensors.cpp
> +        if (std::get<8>(data))
Why not 42? ;) Magic numbers are ugly.

2018-06-15 13:06 UTC, artemsen commented on agent/yadro/sensors.cpp
> +            case 't':
What the magic case?!

2018-06-15 13:06 UTC, artemsen commented on agent/yadro/sensors.cpp
> +    tempSensors.init_mib(
Something wrong. Why didn't you use a factory or an object manager to work with different sensor types through one entry point?

2018-06-15 13:06 UTC, artemsen commented on agent/yadro/software.cpp
> +                                                   0xFF, // Purpose
Magic number: 0xFF. Anyway, why 0xff? Why isn't default 0?

2018-06-15 13:06 UTC, artemsen commented on sdbusplus/helper.hpp
> +    static auto getSubTree(const std::string& path, const Interfaces& ifaces,
I think you can replace all input parameters to auto, too ;)
`auto` in function definition is ambiguous, it's hard to read such code.

2018-06-15 13:06 UTC, artemsen commented on sdevent/event.hpp
> +    int run(uint64_t usec = -1)
I know that systemd interface use such method with negative unsigned number. But for our code I prefer to use macro, something like `#define WAIT_INFINITE -1`

2018-06-18 08:18 UTC, artemsen commented on agent/yadro/sensors.cpp
> +            case 't': // temperature
Use defines for types instead of comment.

2018-06-18 08:21 UTC, artemsen commented on agent/yadro/sensors.cpp
> +                    notifyOid.assign(YADRO_OID(0, 2));
Specify notifyOid as class member.

2018-06-18 08:22 UTC, artemsen commented on agent/yadro/sensors.cpp
> +                case 't': // temperature
Magic 't'

2018-06-18 08:26 UTC, artemsen commented on agent/main.cpp
> +                rc = 1;
Magic constant

2018-06-18 08:47 UTC, artemsen commented on agent/snmp.cpp
> +    int block = 1;
If it is a bool use name like is_blocked.

2018-06-18 08:47 UTC, artemsen commented on agent/yadro/sensors.cpp
> +                char stateOidStr[4096] = {0};
Decrease size

2018-06-18 08:47 UTC, artemsen commented on agent/yadro/sensors.cpp
> +                                std::get<9>(data));
9?

2018-06-18 08:47 UTC, artemsen commented on agent/yadro/sensors.cpp
> +        return static_cast<int>((std::get<Idx>(data) + 0.5) /
Use round()

2018-06-18 10:42 UTC, artemsen submitted a review, later dismissed

2018-06-18 10:57 UTC, artemsen submitted a review, later dismissed

2018-06-19 08:29 UTC, nest1ing commented
@AlexanderAmelkin - your turn

2018-06-19 11:11 UTC, nest1ing commented
I found and fix warning in `smilint YADRO-MIB.txt`

2018-06-19 11:28 UTC, artemsen approved these changes

2018-06-19 12:40 UTC, merged